# Generated by Django 5.2.10 on 2026-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
