# Generated by Django 5.2.10 on 2026-02-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("duration", models.IntegerField(help_text="Duration in days")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
