# Generated by Django 5.2.10 on 2026-02-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services1", "0002_service_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=100)),
                ("categoryDescription", models.TextField()),
                ("categoryStatus", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
    ]
