# Generated by Django 5.2.10 on 2026-02-18 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services1", "0003_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="categoryId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services1.category",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="discount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name="service",
            table="service",
        ),
    ]
