# Generated by Django 5.2.10 on 2026-02-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaignName", models.CharField(max_length=100)),
                ("platform", models.CharField(max_length=50)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("status", models.CharField(max_length=30)),
                ("feedback", models.TextField(blank=True)),
            ],
            options={
                "db_table": "marketing_campaign",
            },
        ),
    ]
