# Generated by Django 5.2.10 on 2026-02-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("salary", models.IntegerField()),
                ("department", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
