# Generated by Django 5.2.10 on 2026-02-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "admin"),
                    ("student", "student"),
                    ("faculty", "faculty"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
