# Generated by Django 5.2.10 on 2026-02-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_studentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productName", models.CharField(max_length=100)),
                ("productPrice", models.DecimalField(decimal_places=2, max_digits=8)),
                ("productQuantity", models.IntegerField()),
                ("productFeedback", models.TextField()),
                ("productColor", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "product",
            },
        ),
    ]
