# Generated by Django 5.2.10 on 2026-02-06 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_marketingcampaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="studentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "studentHobbies",
                    models.CharField(
                        choices=[
                            ("reading", "reading"),
                            ("traveling", "traveling"),
                            ("music", "music"),
                            ("Dancing", "Dancing"),
                        ],
                        max_length=100,
                    ),
                ),
                ("studentAddress", models.CharField(max_length=100)),
                ("studentPhone", models.CharField(max_length=10)),
                ("studentGender", models.CharField(max_length=10)),
                ("studentDob", models.DateField()),
                (
                    "studentId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                    ),
                ),
            ],
            options={
                "db_table": "Student_Profile",
            },
        ),
    ]
