# Generated by Django 5.2.10 on 2026-02-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_studentprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=100)),
                ("catogryDiscription", models.TextField()),
                ("catogryStatus", models.BooleanField(default=True)),
            ],
        ),
    ]
