# Generated by Django 5.2.10 on 2026-02-06 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentprofile",
            old_name="studentId",
            new_name="student",
        ),
        migrations.AlterModelTable(
            name="student",
            table=None,
        ),
        migrations.AlterModelTable(
            name="studentprofile",
            table="student_profile",
        ),
    ]
