# Generated by Django 5.2.10 on 2026-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_rename_studentid_studentprofile_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=50)),
            ],
        ),
    ]
