# Generated by Django 5.2.10 on 2026-02-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_useraccount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useraccount",
            table="User_Account",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("country", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "User_Profile",
            },
        ),
    ]
