# Generated by Django 5.2.10 on 2026-02-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0009_alter_useraccount_table_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("level", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "Course",
            },
        ),
    ]
