# Generated by Django 5.2.10 on 2026-02-06 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0011_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("ad_type", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("status", models.CharField(max_length=20)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_creatives",
                        to="student.marketingcampaign",
                    ),
                ),
            ],
            options={
                "db_table": "AdCreative",
            },
        ),
    ]
