# Generated by Django 5.2.10 on 2026-02-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0013_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceName", models.CharField(max_length=100)),
                ("serviceDescription", models.TextField()),
                ("servicePrice", models.DecimalField(decimal_places=2, max_digits=8)),
                ("serviceDuration", models.IntegerField()),
                ("serviceStatus", models.BooleanField(default=True)),
                ("discount", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.category",
                    ),
                ),
            ],
            options={
                "db_table": "service",
            },
        ),
    ]
