# Generated by Django 5.2.10 on 2026-02-20 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0014_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
