# Generated by Django 5.2.10 on 2026-02-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0002_customerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Category",
            },
        ),
    ]
